### ISSUE TITLE
App Not Installed Error on Android Studio for Mac

### ISSUE THREAD

**Issue by bobby-palko** [cis3296s22/SimpleTunes#45] opened 2022-03-29 17:51 UTC
Walking through the steps to run, I get this error using the Pixel 2 emulator:

![Screen Shot 2022-03-29 at 1 43 23 PM](https://user-images.githubusercontent.com/52588047/160673218-a2584364-47ed-4b62-89ff-715b256d8c82.jpg)

On another note, it took quite a while for the top bar to show as available and not be grayed out (this one for reference):
![image](https://user-images.githubusercontent.com/52588047/160674134-8b3a97da-7092-4fde-9cdf-2fc61d268f73.png)

It might be useful to let users know that may take a while to build, as I started troubleshooting here without realizing things were still working in the background

**Comment by free-mana** [comment] 2022-03-30 17:33
Duplicate of #44 , which has been resolved

**Closed by free-mana** 2022-03-30 17:33 UTC
